.TH FURIUSISOMOUNT 1 "May 6, 2009"
.SH "NAME"
furiusisomount \- mount image files without burning them
.SH "SYNOPSIS"
.B furiusisomount
.SH "DESCRIPTION"
.PP
.B Furius ISO Mount
is a simple application which allows user to mount and manage image files. It
supports a wide variety of formats, like ISO, IMG, BIN, MDF and NRG.
.B Furius ISO Mount
gives user the possibility to mount one or more images to his home directory
with only a click, burn to an optical disk, generate and verify MD5 and SHA1
checksum, maintain an history of previously mounted images and lot of more. 
.PP
.B Furius ISO Mount
has been written with Python and GTK+2, and after installing the application
you can run it from the
.B Applications
menu. 
.PP
.SH "SEE ALSO"
.BR fuseiso (1)
.SH "AUTHOR"
furiusisomount was written by Dean Harris <marcus_furius@hotmail.com>.
.PP
This manual page was written by Alessio Treglia <quadrispro@ubuntu.com>,
for the Debian project (and may be used by others).
